# Irene Remote — connection settings
host: '192.168.1.132'
port: 8086

# Audio input — Seeed 2-Mic Voice Card
buffersize_input: 100
device_input: 'seeed-2mic-voicecard'
blocksize_input: 8000
dtype_input: 'int16'
samplerate_input: 48000
channels_input: 1

# Volume control
volume_step: 5

mixer:
  card: '1'
  control: 'Speaker'

volume:
  min: 0
  middle: 112
  max: 127

  user_min: 76
  user_middle: 112
  user_max: 127

silence_time:
  start: '23:30'
  end: '07:00'
