# server
# ==================================================================
host: '192.168.1.132'
port: '8086'

# input (record)
# ==================================================================
buffersize_input: 100                   # Размер очереди
device_input: 'seeed-2mic-voicecard'    # Устройство захвата звука
blocksize_input: 8000                   # Размер блока
dtype_input: 'int16'                    # Тип данных
samplerate_input: 44100                 # Частота дискретизации
channels_input: 1                       # Количество каналов (моно)

# output (play)
# ==================================================================
device_output: 'seeed-2mic-voicecard'   # Устройство воспроизведения
blocksize_output: 2048                  # Размер блока
dtype_output: 'float32'                 # Тип данных
samplerate_output: 44100                # Частота дискретизации
channels_output: 1                      # Количество каналов (моно)